stripe/example-mobile-backend

- web.rb
r? @jflinter 
A user pointed out that completing a charge doesn't work in the "Custom" example app [0]. I've fixed this, and tested charging in both example apps.
[0] https://github.com/stripe/stripe-ios/issues/461
> Fix charge endpoint for custom example

- web.rb
r? @bdorfman-stripe 
I've tested this against the example app to make sure it properly associates a customer with the charge if there's a customer ID in metadata, and also works if metadata is missing.
> Add customer parameter to webhook charge creation

- web.rb
Changes: Allow the endpoint to charge a specified customer from the client. (The source still has to match the customer we're trying to charge.)
Why: The session logic doesn't work on Android across activities out of the box. I suspect we could do something on the client to move the cookies around to make the session work but I think that would make for a more confusing demo.
Testing: Tested the iOS still makes charges and that the Android demo app when deployed to my example backend.
r? @bg-stripe @mrmcduff-stripe
> Allow endpoint to take specific customer

- web.rb
Allow endpoint to take a JSON response via the request body in addition to form encoded. This will make the app play nicely with the Android app.
tested that both the iOS and android app can make requests successfully.
r? @danj-stripe 
cc: @mrmcduff-stripe
> Make endpoint to form encoded and body params

- web.rb
Currently the endpoint returns JSON data but with a content-type of `text/html`. This can cause issues if the app is configured to check the Content-Type header when decoding the response.
Current behaviour : 
```
curl https://example-karlr-current.herokuapp.com/ephemeral_keys -d "api_version=2018-02-28" -v 2>&1 | grep "Content-Type"
> Content-Type: application/x-www-form-urlencoded
< Content-Type: text/html;charset=utf-8
```
With this PR:
```
curl https://example-karlr.herokuapp.com/ephemeral_keys -d "api_version=2018-02-28" -v 2>&1 | grep "Content-Type"
> Content-Type: application/x-www-form-urlencoded
< Content-Type: application/json
```
> Set Content-Type to 'application/json' for ephemeral_keys endpoint

- web.rb
Bug introduced by #24, when we updated Sinatra from 1.4.7 -> 2.0.1, but missed updating
the json content-type branch.
Fixes #29, alternative to #30 (don't need to maintain `indifferent_hash` backwards compatibility because we specify the Sinatra version in the Gemfile)
> Use `Sinatra::IndifferentHash` instead of `indifferent_hash` due to Sinatra update

- web.rb
This shows off using the `metadata` field to include application-specific information
in the Stripe objects.
These metadata fields can be used for looking up the associated Order/Customer in your
app's backend, given the Order/Customer from Stripe.
> Add `order_id` to Charges and `my_customer_id` to Customers created in sample app.

- web.rb
PaymentIntents do not support providing the `return_url` at creation time anymore.
Instead, they're provided during the call to `confirm`, by the mobile SDK.
> Remove `return_url` from PaymentIntent creation call

- web.rb
While attempting to run the [Stripe Android](https://github.com/stripe/stripe-android) Example app, there was an error creating the payment intent. Viewing the request in the developer console revealed the ruby app is using the latest API version and the following error:
``` json
{
"error": {
"code": "parameter_unknown",
"doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
"message": "Received unknown parameter: allowed_source_types",
"param": "allowed_source_types",
"type": "invalid_request_error"
}
}
```
Checking the API documents revealed that the `allowed_source_types` parameter was changed to `payment_method_types` with [API version 2019-02-11](https://stripe.com/docs/upgrades#2019-02-11).
Ran the example android stripe app and was able to successfully create payment …
> allowed_source_types has been renamed to payment_method_types

- web.rb
**Summary**
Charges have been deprecated in favor of PaymentIntents.
In addition, when we migrate from Sources to PaymentMethods,
we'll be required to use PaymentIntents.
**Motivation**
MOBILE-101
**Testing**
- Manually tested endpoints via curl
- Deployed backend and tested against Android apps
> Migrate to PaymentIntents API

- web.rb
The `authenticate` method creates a Customer; this PR attaches some test card PaymentMethods to it.
Pointed the sample app to local instance:
> Attach test cards to created customers for testing convenience

- web.rb
Instead only return the client_secret which is more secure
> Remove returning PaymentIntent JSON

- web.rb
This allows for the endpoint to be used in conjunction with the standard SDK components that attach PaymentMethods directly to customers. 
**Motivation**
https://jira.corp.stripe.com/browse/MOBILE-131
> Add customer ID as param for create_setup_intent

- web.rb
This is necessary for supporting payment methods other than 'card'
> Add support for passing payment_method_types param in payload

- web.rb
Automatically attach the test credit card numbers from https://stripe.com/docs/mobile/android/authentication#testing as well as `4242`.
> Update automatically attached credit cards for 3DS2 testing

- web.rb
* Passing `amount` and `currency` is ignored, hardcoded on the backend instead. (https://jira.corp.stripe.com/browse/IOS-242) 
* Rename `create_intent` -> `create_payment_intent`
* Instead of `capture_payment`, call `confirm_payment_intent`.  Pass `payment_method_id` instead of `payment_method`.
* Instead of `confirm_payment`, call `confirm_payment_intent`.
* Instead of returning `secret`, if the PI status is...
* `requires_action` -> returns `requires_action: true, secret: abc`
* `requires_capture` or `succeeded` -> returns `success: true`
* anything else -> 500
* Fixed webhooks
Using 3ds1, 3ds2, error cards:
* Custom Integration
[x] Manual confirmation
[x] Automatic confirmation
[x] Setup Intent, SetupIntent Backend confirm
[x] Standard Integration
Tested webhooks for
* PI manual …
> Update to match docs

- web.rb
At this time, SetupIntent only supports the card type
> Force SetupIntent to use payment_method_types=['card']

- web.rb
Adding some additional logging to help diagnose #74.
> Improve error message for missing store items

- web.rb
1/ Passing a comma separated `supported_payment_methods` parameter from the client allows overriding the country<>payment_method config in `payment_methods_for_country()`
e.g. the client can pass `supported_payment_methods=card,afterpay_clearpay` to set custom `payment_method_types` when creating a PaymentIntent
2/ Also added `grabpay` as a payment method to `sg` and `my` according to https://stripe.com/docs/payments/grabpay
> Support custom `payment_method_types` from the client, add grabpay

- app.json
Using the "Deploy to Heroku" button errors due to Heroku defaulting to the latest stack, which doesn't support Ruby 2.6.3:
```
-----> Building on the Heroku-20 stack
-----> Ruby app detected
-----> Installing bundler 1.17.3
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rack
Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.6.3.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.6.3.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
!
! The Ruby version you …
```
> Set heroku stack to 18
